### ISSUE TITLE
tracking issue: axum migration

### ISSUE THREAD

**Issue by syphar** [rust-lang/docs.rs#1900]
Current design idea: 
- axum is the main entrypoint for requests
- when the route is already migrated to axum, we use it, 
- as an axum [`fallback`](https://docs.rs/axum/latest/axum/routing/struct.Router.html#method.fallback) we call the old iron server for the rest 

### details 
- database / storage access will stay sync for now, via `spawn_blocking` (which is the recommended way)
- template engine can stay the same
- preferably we don't have to change tests so it's easier to see if behaviour changed. 

### handler migration status
- [x] `sitemap::sitemapindex_handler`
- [x] `sitemap::sitemap_handler`
- [x] `sitemap::about_builds_handler`
- [x] `statics::static_handler`
- [x] `rustdoc::static_asset_handler`
- [x] `storage_change_detection`
 - [x] `build_details::build_details_handler`
 - [x] `builds::build_list_handler`
 - [x] `crate_details::crate_details_handler`
 - [x] `features::build_features_handler`
 - [x] `metrics::metrics_handler`
 - [x] `releases::activity_handler`
 - [x] `releases::build_queue_handler`
 - [x] `releases::home_page`
 - [x] `releases::owner_handler`
 - [x] `releases::recent_releases_handler`
 - [x] `releases::releases_by_stars_handler`
 - [x] `releases::releases_failures_by_stars_handler`
 - [x] `releases::releases_feed_handler`
 - [x] `releases::releases_recent_failures_handler`
 - [x] `releases::search_handler`
 - [x] `rustdoc::badge_handler`
 - [x] `rustdoc::download_handler`
 - [x] `rustdoc::rustdoc_html_server_handler`
 - [x] `rustdoc::rustdoc_redirector_handler`
 - [x] `rustdoc::target_redirect_handler`
 - [x] `sitemap::about_handler`
 - [x] `source::source_browser_handler`

### links 
- outdated branch with all handlers mostly migrated to axum: https://github.com/rust-lang/docs.rs/compare/master...syphar:docs.rs:new-web-axum ( was used as design experiment, fully working docs)
- [`axum`](https://docs.rs/axum/latest/axum/)
- [`axum-strangler`](https://docs.rs/axum-strangler/latest/axum_strangler/struct.StranglerService.html) as a helper for the migration. 

### issues resolved when finished: 
- #1827 
- #1826 
- #1523 
- #1150 

### issues that we can work on when this is finished: 
- #874

**Comment by syphar** [comment]
strangler performance tests (local): 

### old iron server
```
Running 1m test @ http://localhost:3000/-/static/opensearch.xml
  12 threads and 12 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.89ms   14.51ms 250.11ms   94.31%
    Req/Sec     3.90k     2.00k    8.94k    61.25%
  2790043 requests in 1.00m, 1.80GB read
Requests/sec:  46420.74
Transfer/sec:     30.59MB
```

### simple strangler server, fallback to old iron 
```
Running 1m test @ http://localhost:4000/-/static/opensearch.xml
  12 threads and 12 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.38ms   15.27ms 249.66ms   93.93%
    Req/Sec     2.81k     0.88k    7.73k    76.24%
  2004515 requests in 1.00m, 1.29GB read
Requests/sec:  33354.03
Transfer/sec:     21.98MB
```

### new axum server (not optimized yet)
```
Running 1m test @ http://localhost:3333/-/static/opensearch.xml
  12 threads and 12 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.14ms   15.78ms 250.24ms   94.27%
    Req/Sec     3.43k     1.04k    6.90k    74.32%
  2447013 requests in 1.00m, 1.59GB read
Requests/sec:  40726.37
Transfer/sec:     27.15MB
```

**Comment by syphar** [comment]
strangler performance tests (local), simple database handler 

### old iron server
```
Running 1m test @ http://localhost:3000/crate/sconectl/0.2.13
  12 threads and 12 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.04ms   22.53ms 233.01ms   89.95%
    Req/Sec   265.99    106.13   520.00     66.53%
  189059 requests in 1.00m, 8.41GB read
Requests/sec:   3145.60
Transfer/sec:    143.27MB
```

### simple strangler server, fallback to old iron 
```
Running 1m test @ http://localhost:4000/crate/sconectl/0.2.13
  12 threads and 12 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.44ms   24.04ms 310.05ms   90.19%
    Req/Sec   255.41     99.95   464.00     66.64%
  181229 requests in 1.00m, 8.06GB read
Requests/sec:   3015.47
Transfer/sec:    137.34MB
```

### new axum server (not optimized yet)
```
Running 1m test @ http://localhost:3333/crate/sconectl/0.2.13
  12 threads and 12 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.82ms   18.88ms 251.45ms   92.04%
    Req/Sec   272.72     82.96   434.00     71.63%
  194548 requests in 1.00m, 7.80GB read
Requests/sec:   3237.54
Transfer/sec:    132.98MB
```

**Comment by syphar** [comment]
strangler performance tests (local), simple static handler, more concurrency: 

### old iron server
```
Running 1m test @ http://localhost:3000/-/static/opensearch.xml
  24 threads and 24 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    18.24ms   39.54ms 375.22ms   88.67%
    Req/Sec     1.77k     1.77k   11.14k    83.34%
  2415682 requests in 1.00m, 1.55GB read
Requests/sec:  40196.01
Transfer/sec:     26.49MB
```

### simple strangler server, fallback to old iron 
```
Running 1m test @ http://localhost:4000/-/static/opensearch.xml
  24 threads and 24 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.78ms   16.89ms 342.13ms   92.88%
    Req/Sec     1.46k   574.29     4.37k    69.29%
  2086407 requests in 1.00m, 1.34GB read
Requests/sec:  34738.31
Transfer/sec:     22.89MB
```

### new axum server (not optimized yet)
```
Running 1m test @ http://localhost:3333/-/static/opensearch.xml
  24 threads and 24 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.39ms    5.13ms 128.88ms   97.20%
    Req/Sec     1.43k   220.83     3.33k    75.20%
  2043705 requests in 1.00m, 1.33GB read
Requests/sec:  34030.80
Transfer/sec:     22.69MB
```

**Comment by syphar** [comment]
@jyn514 so this looks like axum-strangler makes it slower, but not to an extend that should worry us. The peaks I sometimes see in grafana are perhaps 10k RPM, so around 166 RPS. Normal load is far, far less.

**Comment by jyn514** [comment]
@syphar looks great! Thanks for testing :)

**Comment by syphar** [comment]
#1963 is merged, closing this issue 

🎉
